### ISSUE TITLE
2.8 Cauchyprodukt Summenvariable

### ISSUE THREAD

**Issue by bits0rcerer** [FelixMoeller3/Zusammenfassung_HM#1]
![Screenshot from 2022-08-31 11-23-50](https://user-images.githubusercontent.com/25325997/187645799-2a1ef1c5-ce07-4db8-b7e4-f48bf4a86930.png)
Müsste das nicht k sein?

**Comment by FelixMoeller3** [comment]
Hast recht, ist gefixt :)
