### ISSUE TITLE
6.2 Kriterien für gleichmäßige Konvergenz - b) Majorantenkriterium von Weierstraß:

### ISSUE THREAD

**Issue by bits0rcerer** [FelixMoeller3/Zusammenfassung_HM#2]
![Screenshot from 2022-08-31 11-46-58](https://user-images.githubusercontent.com/25325997/187650336-42f39cc0-7e23-42c5-9b86-7f01ecffed86.png)

\>= anstat <=?

**Comment by FelixMoeller3** [comment]
Ist gefixt
